#cloud-config

runcmd:
  # print commands, exit on first error
  - set -ex

  # install node 20.x
  - |
    apt-get update && apt-get install -y ca-certificates curl gnupg
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    NODE_MAJOR=20
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    apt-get update && apt-get install -y nodejs

  - |
    cd /etc/mock-server
    npm install

  - systemctl daemon-reload
  - service mock start

write_files:
  - path: /etc/mock-server/app.js
    owner: root:root
    permissions: '0744'
    content: |
      const express = require("express");
      const app = express();
      const port = 80;
      
      app.get("/", (req, res) => {
        const timestamp = new Date().toISOString();
        console.log(`Current timestamp: $${timestamp}`);
        res.status(200).json({msg: "hello world"});
      });
      
      app.listen(port, () => {
        console.log(`Example app listening at http://localhost:$${port}`);
      });

  - path: /etc/mock-server/package.json
    owner: root:root
    permissions: '0744'
    content: |
      {
        "name": "they-mock-server",
        "version": "1.0.0",
        "description": "",
        "main": "app.js",
        "scripts": {
          "start": "node app.js"
        },
        "keywords": [],
        "author": "",
        "license": "ISC",
        "dependencies": {
          "express": "*"
        }
      }

  - path: /etc/systemd/system/mock.service
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=Mock Server
      ConditionPathExists=/etc/mock-server
      After=network.target

      [Service]
      Type=simple
      User=root
      Group=root
      
      WorkingDirectory=/etc/mock-server
      ExecStart=/usr/bin/npm start

      Restart=on-failure
      RestartSec=10

      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=MOCKSERVER

      [Install]
      WantedBy=multi-user.target
