on:
  schedule:
    - cron: "0 8 * * 1-5"
  workflow_dispatch:

name: Send Slack message with open PRs

jobs:
  slack-open-prs:
    name: Slack - open PRs
    runs-on: ubuntu-latest
    steps:
      - name: slack-open-prs
        uses: they-consulting/gh-action-open-pr-slack@main
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ vars.SLACK_CHANNEL }}
